apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mssql-deployment   
spec: 
  replicas: 1 
  selector: 
     matchLabels: 
       app: mssql 
  template: 
    metadata: 
      labels: 
        app: mssql
    spec:
      volumes:
        - name: sqldata-storage
          persistentVolumeClaim:
            claimName: dbclaim
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
        volumeMounts:
        - mountPath: "/var/opt/mssql"
          name: sqldata-storage
      containers:
       - image: mcr.microsoft.com/mssql/server
         name: mssql
         env:
         - name: ACCEPT_EULA
           value: "Y"
         - name: SA_PASSWORD
           value: TestingPassword1
         - name: MSSQL_PID
           value: Developer
         ports:
         - containerPort: 1433
           name: mssql
         volumeMounts:
         - mountPath: "/var/opt/mssql"
           name: sqldata-storage
---
apiVersion: v1 
kind: Service 
metadata: 
  name: mssql-deployment
spec: 
  selector: 
    app: mssql 
  ports: 
    - protocol: TCP 
      port: 1433 
      targetPort: 1433
      nodePort: 31433
  type: LoadBalancer 